Add CSW harvest test
GSA/catalog.data.gov pull request #344
Opened 2021-09-22 18:33 UTC by jbrown-xentity

Add CSW harvest test with public endpoint.
Document for future issues.
Update wait timeout for 10 minutes,
as the csw harvest takes longer to complete.

Related to https://github.com/GSA/datagov-deploy/issues/3376

2021-09-24 22:10 UTC, mogul requested changes

2021-09-24 22:10 UTC, mogul commented on e2e/cypress/integration/000_harvest.spec.js
> +    const cswHarvestSoureName = 'test-harvest-csw'
```suggestion
    const cswHarvestSourceName = 'test-harvest-csw'
```

2021-09-24 22:10 UTC, mogul commented on e2e/cypress/integration/zzz_cleanup.spec.js
> +    const cswHarvestSoureName = 'test-harvest-csw'
```suggestion
    const cswHarvestSourceName = 'test-harvest-csw'
```

2021-09-24 22:10 UTC, mogul commented on e2e/cypress/integration/zzz_cleanup.spec.js
> +        cy.delete_harvest_source(cswHarvestSoureName);
```suggestion
        cy.delete_harvest_source(cswHarvestSourceName);
```

2021-09-24 23:24 UTC, nickumia-reisys requested changes
Found the other references that @mogul missed 👁️

2021-09-24 23:24 UTC, nickumia-reisys commented on e2e/cypress/integration/000_harvest.spec.js
> +                        cswHarvestSoureName,
```suggestion
                        cswHarvestSourceName,
```

2021-09-24 23:24 UTC, nickumia-reisys commented on e2e/cypress/integration/000_harvest.spec.js
> +        cy.location('pathname').should('eq', '/harvest/' + cswHarvestSoureName)
```suggestion
        cy.location('pathname').should('eq', '/harvest/' + cswHarvestSourceName)
```

2021-09-24 23:24 UTC, nickumia-reisys commented on e2e/cypress/integration/000_harvest.spec.js
> +        cy.start_harvest_job(cswHarvestSoureName)
```suggestion
        cy.start_harvest_job(cswHarvestSourceName)
```

2021-09-29 13:28 UTC, FuhuXia commented
Any alternative to adding the external dependency on opentopography.org CSW endpoint?

2021-09-29 14:15 UTC, nickumia-reisys approved these changes

2021-09-29 16:55 UTC, mogul approved these changes

2021-09-29 16:55 UTC, merged